#!/usr/bin/env bash

repo="$(basename $(pwd))"

# Create a github repo for the project
hub create $repo

# Create gitlab project repo
gitlab project create --name $repo

# Set gitlab as mirror
git remote add mirror git@gitlab.com:jonaylor89/$repo.git

# Add a gitlab mirror to the project in the push_commit hook
git pall
