#!/usr/bin/env bash

# store the current dir
CUR_DIR=$(pwd)

update_repo() {
    printf "\n\x1b[95m=-=-={$1}=-=-=\x1b[m\n"
    git --git-dir=$1 --work-tree=$1/.. pull origin master # 2> >(while read line; do printf "\x1b[01;31m$line\x1b[0m\n" >&2 ; done)
}
export -f update_repo

# Let the person running the script know what's going on.
printf "\n\x1b[32mPulling in latest changes for all repositories...\x1b[m\n"

# Find all git repositories and update it to the master latest revision
find ${1:-$HOME/Repos} -name .git -type d | xargs -n1 -P10 -I {} bash -c 'update_repo "$@"' _ {}

printf "\n\033[32mComplete!\033[m\n"
